#include "emp-tool/ir/assets.h"
#include "emp-tool/ir/circuit_asset_dirs.h"  // generated by CMake

#include "emp-tool/runtime/core/utils.h"   // error()

#include <cstdio>
#include <cstdlib>

namespace emp {
namespace circuit {

namespace {

bool file_exists(const std::string& path) {
	FILE* f = std::fopen(path.c_str(), "rb");
	if (!f) return false;
	std::fclose(f);
	return true;
}

void add_dir(std::vector<std::string>& dirs, const std::string& dir) {
	if (dir.empty()) return;
	for (const auto& existing : dirs)
		if (existing == dir) return;
	dirs.push_back(dir);
}

std::string join_path(const std::string& dir, const std::string& file) {
	if (dir.empty() || dir.back() == '/') return dir + file;
	return dir + "/" + file;
}

}  // namespace

const std::vector<std::string>& circuit_asset_dirs() {
	static const std::vector<std::string> dirs = [] {
		std::vector<std::string> out;
		if (const char* e = std::getenv("EMP_CIRCUIT_DIR"))
			add_dir(out, e);
		add_dir(out, EMP_CIRCUIT_ASSET_DIR_BUILD);
		add_dir(out, EMP_CIRCUIT_ASSET_DIR_INSTALL);
		return out;
	}();
	return dirs;
}

std::string find_circuit_asset(const std::string& filename) {
	expecting(!filename.empty(), "find_circuit_asset: empty filename");
	for (const auto& dir : circuit_asset_dirs()) {
		std::string path = join_path(dir, filename);
		if (file_exists(path)) return path;
	}

	expecting(false, [&] {
		std::string msg = "find_circuit_asset: could not find " + filename +
		                  ". Set EMP_CIRCUIT_DIR or install emp-tool circuit assets. Searched:";
		for (const auto& dir : circuit_asset_dirs())
			msg += "\n  " + join_path(dir, filename);
		return msg;
	});
	return {};  // unreachable; keeps the value-returning contract explicit
}

}  // namespace circuit
}  // namespace emp
