name: arm
on: [push, pull_request]

jobs:
  build_arm:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
    runs-on: [self-hosted]
    timeout-minutes: 60
    env:
      BUILD_TYPE: ${{matrix.build_type}}
    steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - uses: actions/checkout@v2.3.0
    - name: Create Build Environment
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE && make
    - name: Test
      shell: bash
      run: ctest -V
