name: arm
on: [push]

jobs:
  build_arm:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
    runs-on: [self-hosted]
    env: 
      BUILD_TYPE: ${{matrix.build_type}}
    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE && make
    - name: Test
      shell: bash
      run: |
        ./bin/prp
        ./bin/prg
        ./bin/mitccrh
        ./bin/bit
        ./bin/int
        ./bin/ecc
        ./bin/f2k
        ./run ./bin/garble
        ./run ./bin/netio
 
