name: CMake
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
    runs-on: ${{ matrix.os }}
    env: 
      BUILD_TYPE: ${{matrix.build_type}}
    steps:
    - name: Compile
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_FLOAT=On .
    - name: Test
      shell: bash
      run: |
        ./bin/prp
        ./bin/prg
        ./bin/mitccrh
        ./bin/bit
        ./bin/int
        ./bin/float
        ./bin/ecc
        ./bin/f2k
